# Water Quality Data Cleaning: EPA Stations

In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import folium
from shapely.geometry import Point
from pathlib import Path

In [2]:
data_path = r'../../../../data/tabular/water-quality/raw'

df_wq = pd.read_csv(f'{data_path}/epa-wq.csv')

'ls' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\owenm\AppData\Local\Temp\ipykernel_2220\1550114532.py:4: DtypeWarning: Columns (0: ActivityMediaSubdivisionName, 1: ActivityRelativeDepthName, 2: ActivityDepthHeightMeasure/MeasureUnitCode, 3: ActivityConductingOrganizationText, 4: ActivityCommentText, 5: HydrologicCondition, 6: HydrologicEvent, 7: SampleCollectionMethod/MethodDescriptionText, 8: MeasureQualifierCode, 9: StatisticalBaseCode, 10: ResultWeightBasisText, 11: ResultTimeBasisText, 12: ResultTemperatureBasisText, 13: SubjectTaxonomicName, 14: SampleTissueAnatomyName, 15: LaboratoryName, 16: ResultLaboratoryCommentText) have mixed types. Specify dtype option on import or set low_memory=False.
  df_wq = pd.read_csv(f'{data_path}/epa-wq.csv')

## Step 1: Inspect the data

Before making any changes to the data, I must inspect the data to gain a better understanding of it.

In [3]:
df_wq.shape          # How many rows and columns?

(118604, 81)

In [4]:
df_wq.head()        # What does the data look like?

,OrganizationIdentifier,OrganizationFormalName,ActivityIdentifier,ActivityTypeCode,ActivityMediaName,ActivityMediaSubdivisionName,ActivityStartDate,ActivityStartTime/Time,ActivityStartTime/TimeZoneCode,ActivityEndDate,...,LaboratoryName,AnalysisStartDate,ResultLaboratoryCommentText,ResultDetectionQuantitationLimitUrl,DetectionQuantitationLimitTypeName,DetectionQuantitationLimitMeasure/MeasureValue,DetectionQuantitationLimitMeasure/MeasureUnitCode,LabSamplePreparationUrl,LastUpdated,ProviderName
0,USGS-IA,USGS Iowa Water Science Center,nwisia.01.02400517,Sample-Routine,Water,Surface Water,2024-01-01,12:00:00,CST,NaN,...,U.S. Geological Survey-Water Resources Discipline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
1,USGS-IA,USGS Iowa Water Science Center,nwisia.01.02400517,Sample-Routine,Water,Surface Water,2024-01-01,12:00:00,CST,NaN,...,U.S. Geological Survey-Water Resources Discipline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
2,USGS-IA,USGS Iowa Water Science Center,nwisia.01.02400551,Sample-Routine,Water,Surface Water,2024-02-26,10:30:00,CST,NaN,...,U.S. Geological Survey-Water Resources Discipline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
3,USGS-IA,USGS Iowa Water Science Center,nwisia.01.02400551,Sample-Routine,Water,Surface Water,2024-02-26,10:30:00,CST,NaN,...,U.S. Geological Survey-Water Resources Discipline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
4,USGS-IA,USGS Iowa Water Science Center,nwisia.01.02400551,Sample-Routine,Water,Surface Water,2024-02-26,10:30:00,CST,NaN,...,U.S. Geological Survey-Water Resources Discipline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS

In [5]:
# What type is each column?
for i, t in enumerate(df_wq.dtypes):
    print(f'{t}: {df_wq.columns[i]}')

str: OrganizationIdentifier
str: OrganizationFormalName
str: ActivityIdentifier
str: ActivityTypeCode
str: ActivityMediaName
str: ActivityMediaSubdivisionName
str: ActivityStartDate
str: ActivityStartTime/Time
str: ActivityStartTime/TimeZoneCode
float64: ActivityEndDate
float64: ActivityEndTime/Time
float64: ActivityEndTime/TimeZoneCode
str: ActivityRelativeDepthName
float64: ActivityDepthHeightMeasure/MeasureValue
str: ActivityDepthHeightMeasure/MeasureUnitCode
float64: ActivityDepthAltitudeReferencePointText
float64: ActivityTopDepthHeightMeasure/MeasureValue
float64: ActivityTopDepthHeightMeasure/MeasureUnitCode
float64: ActivityBottomDepthHeightMeasure/MeasureValue
float64: ActivityBottomDepthHeightMeasure/MeasureUnitCode
str: ProjectIdentifier
str: ProjectName
str: ActivityConductingOrganizationText
str: MonitoringLocationIdentifier
str: MonitoringLocationName
str: ActivityCommentText
float64: SampleAquifer
str: HydrologicCondition
str: HydrologicEvent
float64: ActivityLocation/LatitudeMeasure
float64: ActivityLocation/LongitudeMeasure
str: SampleCollectionMethod/MethodIdentifier
str: SampleCollectionMethod/MethodIdentifierContext
str: SampleCollectionMethod/MethodName
str: SampleCollectionMethod/MethodDescriptionText
str: SampleCollectionEquipmentName
str: ResultIdentifier
str: ResultDetectionConditionText
str: MethodSpeciationName
str: CharacteristicName
str: ResultSampleFractionText
str: ResultMeasureValue
str: ResultMeasure/MeasureUnitCode
str: MeasureQualifierCode
str: ResultStatusIdentifier
str: StatisticalBaseCode
str: ResultValueTypeName
str: ResultWeightBasisText
str: ResultTimeBasisText
str: ResultTemperatureBasisText
float64: ResultParticleSizeBasisText
float64: DataQuality/PrecisionValue
float64: DataQuality/BiasValue
float64: DataQuality/ConfidenceIntervalValue
float64: DataQuality/UpperConfidenceLimitValue
float64: DataQuality/LowerConfidenceLimitValue
str: ResultCommentText
float64: USGSPCode
float64: ResultDepthHeightMeasure/MeasureValue
float64: ResultDepthHeightMeasure/MeasureUnitCode
float64: ResultDepthAltitudeReferencePointText
str: SubjectTaxonomicName
str: SampleTissueAnatomyName
float64: BinaryObjectFileName
float64: BinaryObjectFileTypeCode
float64: ResultFileUrl
str: ResultAnalyticalMethod/MethodIdentifier
str: ResultAnalyticalMethod/MethodIdentifierContext
str: ResultAnalyticalMethod/MethodName
float64: ResultAnalyticalMethod/MethodUrl
str: ResultAnalyticalMethod/MethodDescriptionText
str: LaboratoryName
str: AnalysisStartDate
str: ResultLaboratoryCommentText
str: ResultDetectionQuantitationLimitUrl
str: DetectionQuantitationLimitTypeName
float64: DetectionQuantitationLimitMeasure/MeasureValue
str: DetectionQuantitationLimitMeasure/MeasureUnitCode
float64: LabSamplePreparationUrl
str: LastUpdated
str: ProviderName

In [6]:
df_wq.info()         # Non-null counts + dtypes at a glance

<class 'pandas.DataFrame'>
RangeIndex: 118604 entries, 0 to 118603
Data columns (total 81 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   OrganizationIdentifier                             118604 non-null  str
 1   OrganizationFormalName                             118604 non-null  str
 2   ActivityIdentifier                                 118604 non-null  str
 3   ActivityTypeCode                                   118604 non-null  str
 4   ActivityMediaName                                  118604 non-null  str
 5   ActivityMediaSubdivisionName                       56297 non-null   str
 6   ActivityStartDate                                  118604 non-null  str
 7   ActivityStartTime/Time                             117283 non-null  str
 8   ActivityStartTime/TimeZoneCode                     117283 non-null  str
 9   ActivityEndDate                                    0 non-null       float64
 10  ActivityEndTime/Time                               0 non-null       float64
 11  ActivityEndTime/TimeZoneCode                       0 non-null       float64
 12  ActivityRelativeDepthName                          3431 non-null    str
 13  ActivityDepthHeightMeasure/MeasureValue            6089 non-null    float64
 14  ActivityDepthHeightMeasure/MeasureUnitCode         6089 non-null    str
 15  ActivityDepthAltitudeReferencePointText            0 non-null       float64
 16  ActivityTopDepthHeightMeasure/MeasureValue         0 non-null       float64
 17  ActivityTopDepthHeightMeasure/MeasureUnitCode      0 non-null       float64
 18  ActivityBottomDepthHeightMeasure/MeasureValue      0 non-null       float64
 19  ActivityBottomDepthHeightMeasure/MeasureUnitCode   0 non-null       float64
 20  ProjectIdentifier                                  118560 non-null  str
 21  ProjectName                                        118284 non-null  str
 22  ActivityConductingOrganizationText                 42506 non-null   str
 23  MonitoringLocationIdentifier                       118604 non-null  str
 24  MonitoringLocationName                             118284 non-null  str
 25  ActivityCommentText                                569 non-null     str
 26  SampleAquifer                                      0 non-null       float64
 27  HydrologicCondition                                320 non-null     str
 28  HydrologicEvent                                    408 non-null     str
 29  ActivityLocation/LatitudeMeasure                   118284 non-null  float64
 30  ActivityLocation/LongitudeMeasure                  118284 non-null  float64
 31  SampleCollectionMethod/MethodIdentifier            60943 non-null   str
 32  SampleCollectionMethod/MethodIdentifierContext     60943 non-null   str
 33  SampleCollectionMethod/MethodName                  60943 non-null   str
 34  SampleCollectionMethod/MethodDescriptionText       6207 non-null    str
 35  SampleCollectionEquipmentName                      62350 non-null   str
 36  ResultIdentifier                                   118604 non-null  str
 37  ResultDetectionConditionText                       39811 non-null   str
 38  MethodSpeciationName                               21444 non-null   str
 39  CharacteristicName                                 118604 non-null  str
 40  ResultSampleFractionText                           64384 non-null   str
 41  ResultMeasureValue                                 79838 non-null   str
 42  ResultMeasure/MeasureUnitCode                      87020 non-null   str
 43  MeasureQualifierCode                               416 non-null     str
 44  ResultStatusIdentifier                             118604 non-null  str
 45  StatisticalBaseCode                                1 non-null       str
 46  ResultValueTypeName                                118604 non-null  str
 47  ResultWeightBasisText                              24 non-null      str
 48  ResultTimeBasisText                                958 non-null     str
 49  ResultTemperatureBasisText                         10 non-null      str
 50  ResultParticleSizeBasisText                        0 non-null       float64
 51  DataQuality/PrecisionValue                         0 non-null       float64
 52  DataQuality/BiasValue                              0 non-null       float64
 53  DataQuality/ConfidenceIntervalValue                0 non-null       float64
 54  DataQuality/UpperConfidenceLimitValue              0 non-null       float64
 55  DataQuality/LowerConfidenceLimitValue              0 non-null       float64
 56  ResultCommentText                                  3252 non-null    str
 57  USGSPCode                                          320 non-null     float64
 58  ResultDepthHeightMeasure/MeasureValue              0 non-null       float64
 59  ResultDepthHeightMeasure/MeasureUnitCode           0 non-null       float64
 60  ResultDepthAltitudeReferencePointText              0 non-null       float64
 61  SubjectTaxonomicName                               148 non-null     str
 62  SampleTissueAnatomyName                            60 non-null      str
 63  BinaryObjectFileName                               0 non-null       float64
 64  BinaryObjectFileTypeCode                           0 non-null       float64
 65  ResultFileUrl                                      0 non-null       float64
 66  ResultAnalyticalMethod/MethodIdentifier            74715 non-null   str
 67  ResultAnalyticalMethod/MethodIdentifierContext     74715 non-null   str
 68  ResultAnalyticalMethod/MethodName                  74715 non-null   str
 69  ResultAnalyticalMethod/MethodUrl                   0 non-null       float64
 70  ResultAnalyticalMethod/MethodDescriptionText       26568 non-null   str
 71  LaboratoryName                                     56205 non-null   str
 72  AnalysisStartDate                                  60562 non-null   str
 73  ResultLaboratoryCommentText                        71 non-null      str
 74  ResultDetectionQuantitationLimitUrl                43970 non-null   str
 75  DetectionQuantitationLimitTypeName                 44066 non-null   str
 76  DetectionQuantitationLimitMeasure/MeasureValue     44066 non-null   float64
 77  DetectionQuantitationLimitMeasure/MeasureUnitCode  44066 non-null   str
 78  LabSamplePreparationUrl                            0 non-null       float64
 79  LastUpdated                                        118284 non-null  str
 80  ProviderName                                       118604 non-null  str
dtypes: float64(28), str(53)
memory usage: 73.3 MB

In [7]:
df_wq.describe()     # Summary stats for numeric columns

,ActivityEndDate,ActivityEndTime/Time,ActivityEndTime/TimeZoneCode,ActivityDepthHeightMeasure/MeasureValue,ActivityDepthAltitudeReferencePointText,ActivityTopDepthHeightMeasure/MeasureValue,ActivityTopDepthHeightMeasure/MeasureUnitCode,ActivityBottomDepthHeightMeasure/MeasureValue,ActivityBottomDepthHeightMeasure/MeasureUnitCode,SampleAquifer,...,USGSPCode,ResultDepthHeightMeasure/MeasureValue,ResultDepthHeightMeasure/MeasureUnitCode,ResultDepthAltitudeReferencePointText,BinaryObjectFileName,BinaryObjectFileTypeCode,ResultFileUrl,ResultAnalyticalMethod/MethodUrl,DetectionQuantitationLimitMeasure/MeasureValue,LabSamplePreparationUrl
count,0.0,0.0,0.0,6089.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,320.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44066.000000,0.0
mean,NaN,NaN,NaN,1.005012,NaN,NaN,NaN,NaN,NaN,NaN,...,29901.318750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.813667,NaN
std,NaN,NaN,NaN,2.617023,NaN,NaN,NaN,NaN,NaN,NaN,...,34542.438576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156.132388,NaN
min,NaN,NaN,NaN,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.000000,NaN
25%,NaN,NaN,NaN,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,63.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.050000,NaN
50%,NaN,NaN,NaN,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,452.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000,NaN
75%,NaN,NaN,NaN,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,...,68498.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
max,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,91986.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.000000,NaN

# Step 2: Rename Columns

In [8]:
# Lowercase, strip spaces, replace gaps with underscores
df_wq.columns = df_wq.columns.str.strip().str.replace(" ", "_")
df_wq.columns

Index(['OrganizationIdentifier', 'OrganizationFormalName',
       'ActivityIdentifier', 'ActivityTypeCode', 'ActivityMediaName',
       'ActivityMediaSubdivisionName', 'ActivityStartDate',
       'ActivityStartTime/Time', 'ActivityStartTime/TimeZoneCode',
       'ActivityEndDate', 'ActivityEndTime/Time',
       'ActivityEndTime/TimeZoneCode', 'ActivityRelativeDepthName',
       'ActivityDepthHeightMeasure/MeasureValue',
       'ActivityDepthHeightMeasure/MeasureUnitCode',
       'ActivityDepthAltitudeReferencePointText',
       'ActivityTopDepthHeightMeasure/MeasureValue',
       'ActivityTopDepthHeightMeasure/MeasureUnitCode',
       'ActivityBottomDepthHeightMeasure/MeasureValue',
       'ActivityBottomDepthHeightMeasure/MeasureUnitCode', 'ProjectIdentifier',
       'ProjectName', 'ActivityConductingOrganizationText',
       'MonitoringLocationIdentifier', 'MonitoringLocationName',
       'ActivityCommentText', 'SampleAquifer', 'HydrologicCondition',
       'HydrologicEvent', 'ActivityLocation/LatitudeMeasure',
       'ActivityLocation/LongitudeMeasure',
       'SampleCollectionMethod/MethodIdentifier',
       'SampleCollectionMethod/MethodIdentifierContext',
       'SampleCollectionMethod/MethodName',
       'SampleCollectionMethod/MethodDescriptionText',
       'SampleCollectionEquipmentName', 'ResultIdentifier',
       'ResultDetectionConditionText', 'MethodSpeciationName',
       'CharacteristicName', 'ResultSampleFractionText', 'ResultMeasureValue',
       'ResultMeasure/MeasureUnitCode', 'MeasureQualifierCode',
       'ResultStatusIdentifier', 'StatisticalBaseCode', 'ResultValueTypeName',
       'ResultWeightBasisText', 'ResultTimeBasisText',
       'ResultTemperatureBasisText', 'ResultParticleSizeBasisText',
       'DataQuality/PrecisionValue', 'DataQuality/BiasValue',
       'DataQuality/ConfidenceIntervalValue',
       'DataQuality/UpperConfidenceLimitValue',
       'DataQuality/LowerConfidenceLimitValue', 'ResultCommentText',
       'USGSPCode', 'ResultDepthHeightMeasure/MeasureValue',
       'ResultDepthHeightMeasure/MeasureUnitCode',
       'ResultDepthAltitudeReferencePointText', 'SubjectTaxonomicName',
       'SampleTissueAnatomyName', 'BinaryObjectFileName',
       'BinaryObjectFileTypeCode', 'ResultFileUrl',
       'ResultAnalyticalMethod/MethodIdentifier',
       'ResultAnalyticalMethod/MethodIdentifierContext',
       'ResultAnalyticalMethod/MethodName', 'ResultAnalyticalMethod/MethodUrl',
       'ResultAnalyticalMethod/MethodDescriptionText', 'LaboratoryName',
       'AnalysisStartDate', 'ResultLaboratoryCommentText',
       'ResultDetectionQuantitationLimitUrl',
       'DetectionQuantitationLimitTypeName',
       'DetectionQuantitationLimitMeasure/MeasureValue',
       'DetectionQuantitationLimitMeasure/MeasureUnitCode',
       'LabSamplePreparationUrl', 'LastUpdated', 'ProviderName'],
      dtype='str')

# Step 3: Delete Trivial Columns
Or columns with too many missing values

In [9]:
# Find percent of missing values in each column

percent_missing = df_wq.isnull().sum() * 100 / len(df_wq)
missing_value_df = pd.DataFrame({'column_name': df_wq.columns,
                                 'percent_missing': percent_missing})
missing_value_df.head(20)

,column_name,percent_missing
OrganizationIdentifier,OrganizationIdentifier,0.000000
OrganizationFormalName,OrganizationFormalName,0.000000
ActivityIdentifier,ActivityIdentifier,0.000000
ActivityTypeCode,ActivityTypeCode,0.000000
ActivityMediaName,ActivityMediaName,0.000000
ActivityMediaSubdivisionName,ActivityMediaSubdivisionName,52.533641
ActivityStartDate,ActivityStartDate,0.000000
ActivityStartTime/Time,ActivityStartTime/Time,1.113790
ActivityStartTime/TimeZoneCode,ActivityStartTime/TimeZoneCode,1.113790
ActivityEndDate,ActivityEndDate,100.000000
ActivityEndTime/Time,ActivityEndTime/Time,100.000000
ActivityEndTime/TimeZoneCode,ActivityEndTime/TimeZoneCode,100.000000
ActivityRelativeDepthName,ActivityRelativeDepthName,97.107180
ActivityDepthHeightMeasure/MeasureValue,ActivityDepthHeightMeasure/MeasureValue,94.866109
ActivityDepthHeightMeasure/MeasureUnitCode,ActivityDepthHeightMeasure/MeasureUnitCode,94.866109
ActivityDepthAltitudeReferencePointText,ActivityDepthAltitudeReferencePointText,100.000000
ActivityTopDepthHeightMeasure/MeasureValue,ActivityTopDepthHeightMeasure/MeasureValue,100.000000
ActivityTopDepthHeightMeasure/MeasureUnitCode,ActivityTopDepthHeightMeasure/MeasureUnitCode,100.000000
ActivityBottomDepthHeightMeasure/MeasureValue,ActivityBottomDepthHeightMeasure/MeasureValue,100.000000
ActivityBottomDepthHeightMeasure/MeasureUnitCode,ActivityBottomDepthHeightMeasure/MeasureUnitCode,100.000000

In [10]:
# Replace empty strings and whitespace-only strings with NaN
df_wq.replace(r'^\s*$', pd.NA, regex=True, inplace=True)

# Drop columns where more than 90% of values are missing (NaN/None/pd.NA)
threshold = len(df_wq) * 0.10 # Minimum number of non-missing values required to keep column
df_wq.dropna(axis=1, thresh=threshold, inplace=True)

# Recalculate percent of missing values in each column

percent_missing = df_wq.isnull().sum() * 100 / len(df_wq)
missing_value_df = pd.DataFrame({'column_name': df_wq.columns,
                                 'percent_missing': percent_missing})
missing_value_df

,column_name,percent_missing
OrganizationIdentifier,OrganizationIdentifier,0.000000
OrganizationFormalName,OrganizationFormalName,0.000000
ActivityIdentifier,ActivityIdentifier,0.000000
ActivityTypeCode,ActivityTypeCode,0.000000
ActivityMediaName,ActivityMediaName,0.000000
ActivityMediaSubdivisionName,ActivityMediaSubdivisionName,52.533641
ActivityStartDate,ActivityStartDate,0.000000
ActivityStartTime/Time,ActivityStartTime/Time,1.113790
ActivityStartTime/TimeZoneCode,ActivityStartTime/TimeZoneCode,1.113790
ProjectIdentifier,ProjectIdentifier,0.037098
ProjectName,ProjectName,0.269805
ActivityConductingOrganizationText,ActivityConductingOrganizationText,64.161411
MonitoringLocationIdentifier,MonitoringLocationIdentifier,0.000000
MonitoringLocationName,MonitoringLocationName,0.269805
ActivityLocation/LatitudeMeasure,ActivityLocation/LatitudeMeasure,0.269805
ActivityLocation/LongitudeMeasure,ActivityLocation/LongitudeMeasure,0.269805
SampleCollectionMethod/MethodIdentifier,SampleCollectionMethod/MethodIdentifier,48.616404
SampleCollectionMethod/MethodIdentifierContext,SampleCollectionMethod/MethodIdentifierContext,48.616404
SampleCollectionMethod/MethodName,SampleCollectionMethod/MethodName,48.616404
SampleCollectionEquipmentName,SampleCollectionEquipmentName,47.430104
ResultIdentifier,ResultIdentifier,0.000000
ResultDetectionConditionText,ResultDetectionConditionText,66.433678
MethodSpeciationName,MethodSpeciationName,81.919665
CharacteristicName,CharacteristicName,0.000000
ResultSampleFractionText,ResultSampleFractionText,45.715153
ResultMeasureValue,ResultMeasureValue,32.685238
ResultMeasure/MeasureUnitCode,ResultMeasure/MeasureUnitCode,26.629793
ResultStatusIdentifier,ResultStatusIdentifier,0.000000
ResultValueTypeName,ResultValueTypeName,0.000000
ResultAnalyticalMethod/MethodIdentifier,ResultAnalyticalMethod/MethodIdentifier,37.004654
ResultAnalyticalMethod/MethodIdentifierContext,ResultAnalyticalMethod/MethodIdentifierContext,37.004654
ResultAnalyticalMethod/MethodName,ResultAnalyticalMethod/MethodName,37.004654
ResultAnalyticalMethod/MethodDescriptionText,ResultAnalyticalMethod/MethodDescriptionText,77.599406
LaboratoryName,LaboratoryName,52.611210
AnalysisStartDate,AnalysisStartDate,48.937641
ResultDetectionQuantitationLimitUrl,ResultDetectionQuantitationLimitUrl,62.927051
DetectionQuantitationLimitTypeName,DetectionQuantitationLimitTypeName,62.846110
DetectionQuantitationLimitMeasure/MeasureValue,DetectionQuantitationLimitMeasure/MeasureValue,62.846110
DetectionQuantitationLimitMeasure/MeasureUnitCode,DetectionQuantitationLimitMeasure/MeasureUnitCode,62.846110
LastUpdated,LastUpdated,0.269805
ProviderName,ProviderName,0.000000

In [41]:
# Re-create the df_wq data frame to include only necessary columns

df_wq = df_wq[[
 "ActivityIdentifier", 
 "ActivityStartDate", 
 "ActivityStartTime/Time",  
 "MonitoringLocationIdentifier", 
 "MonitoringLocationName", 
 "ActivityLocation/LatitudeMeasure", 
 "ActivityLocation/LongitudeMeasure",
 "CharacteristicName",
 "ResultMeasureValue",
 "ResultMeasure/MeasureUnitCode",
 "ResultValueTypeName",
 "AnalysisStartDate",
 "LastUpdated"
]]

# Step 4: Fix Data Types

Print data types of existing columns

In [42]:
#for i, t in enumerate(df_wq.dtypes):
 #   print(f'{t}: {df_wq.columns[i]}')
df_wq.dtypes

ActivityIdentifier                              str
ActivityStartDate                               str
ActivityStartTime/Time                          str
MonitoringLocationIdentifier                    str
MonitoringLocationName                          str
ActivityLocation/LatitudeMeasure            float64
ActivityLocation/LongitudeMeasure           float64
CharacteristicName                              str
ResultMeasureValue                          float64
ResultMeasure/MeasureUnitCode                   str
ResultValueTypeName                             str
AnalysisStartDate                    datetime64[us]
LastUpdated                                     str
dtype: object

In [ ]:
# Type conversions are handled in the cell below

In [ ]:
# Combine date + time into a single datetime column
df_wq["ActivityStartDateTime"] = df_wq["ActivityStartDate"] + " " + df_wq["ActivityStartTime/Time"]
df_wq["ActivityStartDateTime"] = pd.to_datetime(df_wq["ActivityStartDateTime"], errors="coerce")
df_wq.drop(["ActivityStartDate", "ActivityStartTime/Time"], axis=1, inplace=True)

# Convert remaining date columns to datetime
df_wq["AnalysisStartDate"] = pd.to_datetime(df_wq["AnalysisStartDate"], errors="coerce")
df_wq["LastUpdated"] = pd.to_datetime(df_wq["LastUpdated"], errors="coerce")

# Convert measurement value to float
df_wq["ResultMeasureValue"] = pd.to_numeric(df_wq["ResultMeasureValue"], errors="coerce")

df_wq.dtypes

In [45]:
df_wq.dtypes

ActivityIdentifier                              str
ActivityStartDate                               str
ActivityStartTime/Time                          str
MonitoringLocationIdentifier                    str
MonitoringLocationName                          str
ActivityLocation/LatitudeMeasure            float64
ActivityLocation/LongitudeMeasure           float64
CharacteristicName                              str
ResultMeasureValue                          float64
ResultMeasure/MeasureUnitCode                   str
ResultValueTypeName                             str
AnalysisStartDate                    datetime64[us]
LastUpdated                                     str
ActivityStartDateTime                datetime64[us]
dtype: object

In [ ]:
# Step 5: Handle Missing Values
# Drop rows missing the key columns needed for analysis
df_wq.dropna(subset=["MonitoringLocationIdentifier", "CharacteristicName", "ResultMeasureValue"], inplace=True)

print(f"Rows remaining: {len(df_wq):,}")
print("\nMissing values per column:")
print(df_wq.isnull().sum())

In [ ]:
# Step 6: Save Cleaned Data
import os
out_path = '../../../../data/tabular/water-quality/cleaned'
os.makedirs(out_path, exist_ok=True)
df_wq.to_csv(f'{out_path}/epa-wq-clean.csv', index=False)
print(f"Saved {len(df_wq):,} rows → {out_path}/epa-wq-clean.csv")